stages:
  - preparation
  - testing
  - deploy
#   - building
#   - security

image: edbizarro/gitlab-ci-pipeline-php:7.4

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: preparation
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

# yarn:
#   stage: preparation
#   script:
#     - yarn --version
#     - yarn install --pure-lockfile
#   artifacts:
#     paths:
#       - node_modules/
#     expire_in: 1 days
#     when: always
#   cache:
#     paths:
#       - node_modules/

# build-assets:
#   stage: building
#   # Download the artifacts for these jobs
#   dependencies:
#     - composer
#     - yarn
#   script:
#     - yarn --version
#     - yarn run production --progress false
#   artifacts:
#     paths:
#       - public/css/
#       - public/js/
#       - public/fonts/
#       - public/mix-manifest.json
#     expire_in: 1 days
#     when: always

phpunit:
  stage: testing
  dependencies:
    # - build-assets
    - composer
  script:
    - php -v
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak
    - echo "" | sudo tee /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - ./vendor/phpunit/phpunit/phpunit --version
    - composer run test
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

codestyle:
  stage: testing
  image: lorisleiva/laravel-docker
  script:
    - composer run cs
  dependencies:
    - composer

lint:
  stage: testing
  image: lorisleiva/laravel-docker
  script:
    - composer run lint
  dependencies:
    - composer

# #Only PHP > 7.3
# #phpcpd:
# #  stage: testing
# #  script:
# #    - test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
# #    - php phpcpd.phar app/ --min-lines=50
# #  dependencies: []
# #  cache:
# #    paths:
# #      - phpcpd.phar

# sensiolabs:
#   stage: security
#   script:
#     - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
#     - cd security-checker
#     - composer install
#     - php security-checker security:check ../composer.lock
#   dependencies: []
#   cache:
#     paths:
#       - security-checker/

deploy:
  stage: deploy
  image: mwienk/docker-git-ftp
  dependencies:
    - phpunit
    - codestyle
    - lint
    # - sensiolabs
  script:
    #--parallel=10
    - apt-get update -qq && apt-get install -y -qq lftp
    - >
      lftp -c "set ftp:ssl-allow no; open -u $FTP_USER,$FTP_PASS $FTP_HOST;
      mirror -Rev ./ domains/erp.pessoaweb.com.br
      --ignore-time
      --exclude       .env
      --exclude       vendor/autoload.php
      --exclude       .git/
      --exclude-glob  vendor/*"
  only:
    - master
