<?php

namespace App\Models;

use BRCas\Laravel\Traits\Entities\Uuid;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;

class Store extends Model
{
    use Uuid;

    public $fillable = ['name', 'domain', 'document'];

    public static function create($attributes)
    {
        $obj = self::query()->create($attributes);

        $attributes['user']['password'] = Hash::make($attributes['user']['password']);

        $obj->users()->create($attributes['user'])->givePermissionTo('super admin');

        return $obj;
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($obj) {
            $obj->client_id = sha1($obj->id);
            $obj->secret_id = sha1($obj->key);
        });
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function setDocumentAttribute($value)
    {
        $this->attributes['document'] = onlyNumber($value);
    }
}
